version: '3.8'
services:
  # dev-db:
  #   container_name: postgres_container
  #   image: postgres:13
  #   ports:
  #     - 5434:5432
  #   restart: always
  #   environment:
  #     POSTGRES_USER: admin
  #     POSTGRES_PASSWORD: admin
  #     POSTGRES_DB: test_db
  # pgadmin:
  #   container_name: pgadmin4_container
  #   image: dpage/pgadmin4
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: root
  #   ports:
  #     - '5050:80'
  mysql-server:
    image: mysql:8.0
    container_name: MySQL
    restart: always
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_DATABASE=social_media_app_db
      - MYSQL_USER=howard
      - MYSQL_PASSWORD=howard
      - MYSQL_ROOT_PASSWORD=howard
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 5012:3306
  phpmyadmin:
    image: phpmyadmin:5.2.0
    container_name: PhpMyAdmin
    restart: always
    ports:
      - 5013:80
    environment:
      - PMA_ARBITRARY=1
volumes:
  mysql:
#   test-db:
#     image: postgres:13
#     ports:
#       - 5435:5432
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: 123
#       POSTGRES_DB: nest
#     networks:
#       - freecodecamp
# networks:
#   freecodecamp:
