version: '3.8'
services:
  apiserver:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: mhwai/social-media-api-server-2023:v2
    command: npm start
    env_file: .env
    ports:
      - '8000:8000'
#   mysql-server:
#     image: mysql:8.0
#     container_name: MySQL
#     restart: always
#     cap_add:
#       - SYS_NICE
#     environment:
#       - MYSQL_DATABASE=social_media_db
#       - MYSQL_USER=howard
#       - MYSQL_PASSWORD=howard
#       - MYSQL_ROOT_PASSWORD=howard
#     volumes:
#       - mysql:/var/lib/mysql
#     ports:
#       - 5012:3306
#   phpmyadmin:
#     image: phpmyadmin:5.2.0
#     container_name: PhpMyAdmin
#     restart: always
#     ports:
#       - 5013:80
#     environment:
#       - PMA_ARBITRARY=1
# volumes:
#   mysql:
